# dbt project configuration for cap111 UK Banking Analytics
name: 'capital_one_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'capital_one_snowflake'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  capital_one_analytics:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      core:
        +materialized: table
      finance:
        +materialized: table
      risk:
        +materialized: table
      customer:
        +materialized: table

# Snapshot configurations
snapshots:
  capital_one_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at

# Test configurations
tests:
  +store_failures: true
  +schema: test_failures

# Documentation
docs:
  +node_color: "#1f8b4c"

vars:
  # Timezone for the project
  timezone: 'Europe/London'
  
  # Date range for incremental models
  start_date: '2020-01-01'
  
  # Business logic variables
  min_account_balance: 0
  high_value_transaction_threshold: 10000
  credit_risk_threshold: 0.7
  
  # PII masking (set to true in production)
  mask_pii: false
